# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\settings_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(548, 450)
        self.gridLayout_6 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_6.setObjectName("gridLayout_6")
        
        # GroupBox for background and gear images
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setTitle("Image Settings")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setText("Background Image:")
        self.label.setObjectName("label")
        self.gridLayout_5.addWidget(self.label, 0, 0, 1, 1)
        
        self.lineEdit_background = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_background.setObjectName("lineEdit_background")
        self.gridLayout_5.addWidget(self.lineEdit_background, 0, 1, 1, 1)
        
        self.toolButton_background = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_background.setText("...")
        self.toolButton_background.setObjectName("toolButton_background")
        self.gridLayout_5.addWidget(self.toolButton_background, 0, 2, 1, 1)
        
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setText("Gear Icon:")
        self.label_2.setObjectName("label_2")
        self.gridLayout_5.addWidget(self.label_2, 1, 0, 1, 1)
        
        self.lineEdit_gear = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_gear.setObjectName("lineEdit_gear")
        self.gridLayout_5.addWidget(self.lineEdit_gear, 1, 1, 1, 1)
        
        self.toolButton_gear = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_gear.setText("...")
        self.toolButton_gear.setObjectName("toolButton_gear")
        self.gridLayout_5.addWidget(self.toolButton_gear, 1, 2, 1, 1)
        
        self.pushButton_imageFolder = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_imageFolder.setText("Open Folders")
        self.pushButton_imageFolder.setObjectName("pushButton_imageFolder")
        self.gridLayout_5.addWidget(self.pushButton_imageFolder, 2, 0, 1, 1)
        
        self.pushButton_randomize = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_randomize.setText("Randomize")
        self.pushButton_randomize.setObjectName("pushButton_randomize")
        self.gridLayout_5.addWidget(self.pushButton_randomize, 2, 1, 1, 1)
        
        self.gridLayout_6.addWidget(self.groupBox, 0, 0, 1, 2)

        # GroupBox for general visibility settings
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setTitle("Visibility")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        
        self.checkBox_reviewer = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_reviewer.setText("Show in Reviewer")
        self.checkBox_reviewer.setObjectName("checkBox_reviewer")
        self.gridLayout_4.addWidget(self.checkBox_reviewer, 0, 0, 1, 1)
        
        self.checkBox_toolbar = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_toolbar.setText("Show in Toolbars")
        self.checkBox_toolbar.setObjectName("checkBox_toolbar")
        self.gridLayout_4.addWidget(self.checkBox_toolbar, 1, 0, 1, 1)
        
        self.checkBox_topbottom = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_topbottom.setText("Toolbar Top/Bottom")
        self.checkBox_topbottom.setObjectName("checkBox_topbottom")
        self.gridLayout_4.addWidget(self.checkBox_topbottom, 2, 0, 1, 1)
        
        self.gridLayout_6.addWidget(self.groupBox_2, 1, 0, 1, 1)

        # GroupBox for Opacity
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setTitle("Opacity")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setText("Main:")
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 1)
        
        self.Slider_main = QtWidgets.QSlider(self.groupBox_3)
        self.Slider_main.setMaximum(100)
        self.Slider_main.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_main.setObjectName("Slider_main")
        self.gridLayout_3.addWidget(self.Slider_main, 0, 1, 1, 1)
        
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setText("Review:")
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 1, 0, 1, 1)
        
        self.Slider_review = QtWidgets.QSlider(self.groupBox_3)
        self.Slider_review.setMaximum(100)
        self.Slider_review.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_review.setObjectName("Slider_review")
        self.gridLayout_3.addWidget(self.Slider_review, 1, 1, 1, 1)
        
        self.gridLayout_6.addWidget(self.groupBox_3, 1, 1, 1, 1)

        # GroupBox for Layout
        self.groupBox_4 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_4.setTitle("Layout")
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setText("Attachment:")
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        
        self.comboBox_attachment = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_attachment.addItem("fixed")
        self.comboBox_attachment.addItem("scroll")
        self.comboBox_attachment.setObjectName("comboBox_attachment")
        self.gridLayout_2.addWidget(self.comboBox_attachment, 0, 1, 1, 1)
        
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setText("Size:")
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 2, 1, 1)
        
        self.comboBox_size = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_size.addItem("cover")
        self.comboBox_size.addItem("contain")
        self.comboBox_size.setObjectName("comboBox_size")
        self.gridLayout_2.addWidget(self.comboBox_size, 0, 3, 1, 1)
        
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setText("Position:")
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 1, 0, 1, 1)
        
        self.comboBox_position = QtWidgets.QComboBox(self.groupBox_4)
        positions = ["left top", "center top", "right top", "right", "left", "center", "left bottom", "center bottom", "right bottom"]
        for pos in positions:
            self.comboBox_position.addItem(pos)
        self.comboBox_position.setObjectName("comboBox_position")
        self.gridLayout_2.addWidget(self.comboBox_position, 1, 1, 1, 1)
        
        self.label_9 = QtWidgets.QLabel(self.groupBox_4)
        self.label_9.setText("Scale:")
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 1, 2, 1, 1)
        
        self.scaleBox = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.scaleBox.setDecimals(1)
        self.scaleBox.setMinimum(0.1)
        self.scaleBox.setSingleStep(0.1)
        self.scaleBox.setProperty("value", 1.0)
        self.scaleBox.setObjectName("scaleBox")
        self.gridLayout_2.addWidget(self.scaleBox, 1, 3, 1, 1)
        
        self.gridLayout_6.addWidget(self.groupBox_4, 2, 0, 1, 2)

        # GroupBox for Colors
        self.groupBox_5 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_5.setTitle("Colors")
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout.setObjectName("gridLayout")
        
        self.label_11 = QtWidgets.QLabel(self.groupBox_5)
        self.label_11.setText("Main:")
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 0, 0, 1, 1)
        
        self.lineEdit_color_main = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_color_main.setObjectName("lineEdit_color_main")
        self.gridLayout.addWidget(self.lineEdit_color_main, 0, 1, 1, 1)
        
        self.toolButton_color_main = QtWidgets.QToolButton(self.groupBox_5)
        self.toolButton_color_main.setText("...")
        self.toolButton_color_main.setObjectName("toolButton_color_main")
        self.gridLayout.addWidget(self.toolButton_color_main, 0, 2, 1, 1)
        
        self.label_12 = QtWidgets.QLabel(self.groupBox_5)
        self.label_12.setText("Top:")
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 0, 3, 1, 1)
        
        self.lineEdit_color_top = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_color_top.setObjectName("lineEdit_color_top")
        self.gridLayout.addWidget(self.lineEdit_color_top, 0, 4, 1, 1)
        
        self.toolButton_color_top = QtWidgets.QToolButton(self.groupBox_5)
        self.toolButton_color_top.setText("...")
        self.toolButton_color_top.setObjectName("toolButton_color_top")
        self.gridLayout.addWidget(self.toolButton_color_top, 0, 5, 1, 1)
        
        self.label_13 = QtWidgets.QLabel(self.groupBox_5)
        self.label_13.setText("Bottom:")
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 1, 3, 1, 1)
        
        self.lineEdit_color_bottom = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_color_bottom.setObjectName("lineEdit_color_bottom")
        self.gridLayout.addWidget(self.lineEdit_color_bottom, 1, 4, 1, 1)
        
        self.toolButton_color_bottom = QtWidgets.QToolButton(self.groupBox_5)
        self.toolButton_color_bottom.setText("...")
        self.toolButton_color_bottom.setObjectName("toolButton_color_bottom")
        self.gridLayout.addWidget(self.toolButton_color_bottom, 1, 5, 1, 1)
        
        self.gridLayout_6.addWidget(self.groupBox_5, 3, 0, 1, 2)

        # OK and Restore buttons
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.RestoreButton = QtWidgets.QPushButton(Dialog)
        self.RestoreButton.setText("Restore Default")
        self.RestoreButton.setObjectName("RestoreButton")
        self.buttonLayout.addWidget(self.RestoreButton)
        
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttonLayout.addItem(spacerItem)
        
        self.OkButton = QtWidgets.QPushButton(Dialog)
        self.OkButton.setText("OK")
        self.OkButton.setObjectName("OkButton")
        self.buttonLayout.addWidget(self.OkButton)
        
        self.gridLayout_6.addLayout(self.buttonLayout, 4, 0, 1, 2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Custom Background Settings"))
